#!/usr/bin/env python
"""Generate structured reference entries without HTTP (offline/network-restricted)."""
import json
from datetime import datetime
from pathlib import Path

OUTPUT = Path(__file__).resolve().parent.parent.parent / "docs" / "standards" / "downloads"
OUTPUT.mkdir(parents=True, exist_ok=True)

# All 100+ standards with metadata
ALL_STANDARDS = [
    # --- AI Regulatory ---
    ("ISO-14971-2019", "ISO 14971:2019 Medical devices - Risk management", "P0", "iso",
     "https://www.iso.org/standard/72704.html", "Copyright - purchase required"),
    ("IEC-62304-2006", "IEC 62304:2006+A1:2015 Medical device software lifecycle", "P0", "iec",
     "https://www.iso.org/standard/64686.html", "Copyright - purchase required"),
    ("IEC-62366-2015", "IEC 62366:2015 Medical devices - Usability engineering", "P1", "iec",
     "https://www.iso.org/standard/63179.html", "Copyright - purchase required"),
    ("NMPA-AI-REG-2022", "AI Medical Device Registration Review Guideline 2022", "P0", "nmpa",
     "https://www.nmpa.gov.cn/ylqx/ylqxggtg/20220309111021184.html", "Free - Chinese only"),
    ("ISO-13485-2016", "ISO 13485:2016 Medical devices - QMS", "P1", "iso",
     "https://www.iso.org/standard/59752.html", "Copyright - purchase required"),

    # --- AI Research ---
    ("CONSORT-AI", "CONSORT-AI: Reporting clinical trials evaluating AI", "P0", "pmc",
     "https://www.nature.com/articles/s41591-020-1034-x", "Free PMC"),
    ("SPIRIT-AI", "SPIRIT-AI: Trial protocols evaluating AI interventions", "P0", "pmc",
     "https://www.nature.com/articles/s41591-020-1037-7", "Free PMC"),
    ("TRIPOD-AI", "TRIPOD+AI: Prediction model studies using AI", "P0", "bmj",
     "https://www.bmj.com/content/385/bmj-2023-078378", "Free"),
    ("DECIDE-AI", "DECIDE-AI: Early clinical evaluation of decision-support", "P1", "nature",
     "https://www.nature.com/articles/s41591-022-01772-9", "Free PMC"),
    ("STARD-AI", "STARD-AI: Reporting diagnostic accuracy studies using AI", "P1", "bmj",
     "https://www.bmj.com/content/387/bmj-2024-080030", "Free"),

    # --- AI Ethics ---
    ("WHO-AI-ETHICS-2021", "WHO Ethics and governance of AI for health", "P0", "who",
     "https://www.who.int/publications/i/item/9789240029200", "Free PDF"),
    ("CN-AI-GOVERNANCE", "China New Generation AI Governance Principles", "P0", "gov-cn",
     "https://www.gov.cn/xinwen/2019-06/17/content_5401006.htm", "Free"),
    ("CN-ETHICS-REVIEW", "Science and Technology Ethics Review Measures", "P0", "gov-cn",
     "https://www.most.gov.cn/xxgk/xinxifenlei/fdzdgknr/fgzc/gfxwj/gfxwj2023/202310/t20231008_188968.html", "Free"),
    ("NIST-AI-RMF-1.0", "NIST AI Risk Management Framework 1.0", "P1", "nist",
     "https://www.nist.gov/itl/ai-risk-management-framework", "Free"),
    ("EU-AI-ACT", "EU AI Act (Regulation 2024/1689)", "P1", "eu",
     "https://eur-lex.europa.eu/eli/reg/2024/1689", "Free"),

    # --- Data Interoperability ---
    ("FHIR-R4", "HL7 FHIR Release 4", "P0", "hl7",
     "https://hl7.org/fhir/R4/", "Free"),
    ("SNOMED-CT", "SNOMED CT", "P0", "snomed",
     "https://www.snomed.org/", "Free for member countries via NLM"),
    ("LOINC", "LOINC", "P0", "loinc",
     "https://loinc.org/downloads/", "Free"),
    ("DICOM-3.0-2024", "DICOM PS3.1-3.22 2024", "P1", "nema",
     "https://www.dicomstandard.org/current", "Free"),
    ("HL7-v2.9", "HL7 Version 2.9", "P1", "hl7",
     "https://www.hl7.org/implement/standards/product_brief.cfm?product_id=185", "Free"),
    ("IHE-TF", "IHE Technical Frameworks", "P1", "ihe",
     "https://www.ihe.net/resources/technical_frameworks/", "Free"),
    ("OMOP-CDM", "OMOP Common Data Model v5.4", "P1", "ohdsi",
     "https://ohdsi.github.io/CommonDataModel/", "Free"),
    ("CDA-R2", "HL7 CDA Release 2", "P1", "hl7",
     "https://www.hl7.org/implement/standards/product_brief.cfm?product_id=7", "Free"),

    # --- Cardiology ---
    ("ESC-CMP-2023", "2023 ESC Guidelines for cardiomyopathies", "P0", "esc",
     "https://academic.oup.com/eurheartj/article/44/37/3503/7246606", "Free"),
    ("ESC-AFIB-2024", "2024 ESC Guidelines for atrial fibrillation", "P0", "esc",
     "https://academic.oup.com/eurheartj/article/45/36/3314/7738915", "Free"),
    ("ESC-HF-2021", "2021 ESC Guidelines for heart failure", "P0", "esc",
     "https://academic.oup.com/eurheartj/article/42/36/3599/6358045", "Free"),
    ("AHA-ACC-HF-2022", "2022 AHA/ACC/HFSA Guideline for HF", "P0", "aha",
     "https://www.ahajournals.org/doi/10.1161/CIR.0000000000001063", "Free"),
    ("AHA-ACC-VALVE-2020", "2020 ACC/AHA Valvular Heart Disease guideline", "P0", "aha",
     "https://www.ahajournals.org/doi/10.1161/CIR.0000000000000923", "Free"),
    ("ESC-EACTS-VALVE-2021", "2021 ESC/EACTS Valvular Heart Disease guideline", "P0", "esc",
     "https://academic.oup.com/eurheartj/article/43/7/561/6358470", "Free"),
    ("AHA-ACC-HCM-2020", "2020 AHA/ACC Hypertrophic Cardiomyopathy guideline", "P1", "aha",
     "https://www.ahajournals.org/doi/10.1161/CIR.0000000000000937", "Free"),
    ("AHA-ASA-STROKE-2019", "2019 AHA/ASA Acute Ischemic Stroke guideline", "P0", "aha",
     "https://www.ahajournals.org/doi/10.1161/STR.0000000000000211", "Free"),
    ("ESC-PE-2019", "2019 ESC Guidelines on Acute Pulmonary Embolism", "P1", "esc",
     "https://academic.oup.com/eurheartj/article/41/4/543/5556136", "Free"),

    # --- Nephrology ---
    ("KDIGO-AKI-2024", "KDIGO 2024 Acute Kidney Injury guideline", "P0", "kdigo",
     "https://kdigo.org/guidelines/acute-kidney-injury/", "Free PDF"),
    ("KDIGO-CKD-2024", "KDIGO 2024 CKD guideline", "P1", "kdigo",
     "https://kdigo.org/guidelines/ckd-evaluation-and-management/", "Free PDF"),
    ("KDIGO-GN-2024", "KDIGO 2024 Glomerular Diseases guideline", "P1", "kdigo",
     "https://kdigo.org/guidelines/glomerular-diseases/", "Free PDF"),

    # --- Respiratory ---
    ("GOLD-COPD-2024", "GOLD 2024 Global Strategy for COPD", "P0", "gold",
     "https://goldcopd.org/2024-gold-report/", "Free PDF"),
    ("GINA-ASTHMA-2024", "GINA 2024 Global Strategy for Asthma", "P1", "gina",
     "https://ginasthma.org/2024-report/", "Free PDF"),
    ("ATS-ERS-PFT-2022", "ATS/ERS Standardisation of Lung Function Testing", "P1", "ers",
     "https://erj.ersjournals.com/content/60/1/2101499", "Free"),

    # --- Endocrinology ---
    ("ADA-DM-2025", "ADA Standards of Care in Diabetes 2025", "P0", "ada",
     "https://diabetesjournals.org/care/issue/48/Supplement_1", "Free"),
    ("ESH-HTN-2023", "2023 ESH Guidelines for Hypertension", "P0", "esh",
     "https://journals.lww.com/jhypertension/fulltext/2023/12000", "Free"),
    ("CN-PA-CONSENSUS-2020", "Primary Aldosteronism Chinese Expert Consensus 2020", "P0", "cmj",
     "http://medjournals.cn/", "Chinese journal access"),

    # --- Oncology ---
    ("NCCN-BREAST-2025", "NCCN Breast Cancer v2.2025", "P0", "nccn",
     "https://www.nccn.org/guidelines/guidelines-detail?category=1&id=1419", "Free registration"),
    ("NCCN-GASTRIC-2025", "NCCN Gastric Cancer v2.2025", "P0", "nccn",
     "https://www.nccn.org/guidelines/guidelines-detail?category=1&id=1443", "Free registration"),
    ("NCCN-COLON-2025", "NCCN Colon Cancer v2.2025", "P0", "nccn",
     "https://www.nccn.org/guidelines/guidelines-detail?category=1&id=1428", "Free registration"),
    ("NCCN-RECTAL-2025", "NCCN Rectal Cancer v1.2025", "P1", "nccn",
     "https://www.nccn.org/guidelines/guidelines-detail?category=1&id=1461", "Free registration"),
    ("ASCO-CHEMO-SAFETY", "ASCO/ONS Chemotherapy Safety Standards", "P0", "asco",
     "https://ascopubs.org/doi/10.1200/JCO.2016.70.1473", "Free"),
    ("ESMO-GASTRIC-2024", "ESMO Gastric Cancer guideline 2024", "P1", "esmo",
     "https://www.esmo.org/guidelines/esmo-clinical-practice-guideline-gastric-cancer", "Free"),
    ("CSCO-BREAST-2024", "CSCO Breast Cancer guideline 2024", "P1", "csco",
     "http://www.csco.org.cn/", "Chinese - may require registration"),

    # --- Neurology & Neurosurgery ---
    ("TOAST-1993", "TOAST Classification of Subtypes of Acute Ischemic Stroke", "P0", "ninds",
     "https://pubmed.ncbi.nlm.nih.gov/7678184/", "Free - classic reference"),
    ("WFNS-SAH", "WFNS Grading Scale for Subarachnoid Hemorrhage", "P0", "wfns",
     "https://pubmed.ncbi.nlm.nih.gov/3338060/", "Free"),
    ("HUNT-HESS", "Hunt-Hess Classification of SAH", "P1", "ns",
     "https://pubmed.ncbi.nlm.nih.gov/?term=Hunt+Hess+grade+SAH", "Free"),
    ("WHO-CNS5-2021", "WHO Classification of Tumours of the CNS 5th Ed 2021", "P1", "who",
     "https://publications.iarc.fr/Book-And-Report-Series/Who-Classification-Of-Tumours/Central-Nervous-System-Tumours-2021", "Free online, print purchase"),
    ("GCS-SCALE", "Glasgow Coma Scale (GCS) - standard neurological assessment", "P1", "gcs",
     "https://www.glasgowcomascale.org/", "Free"),
    ("NIHSS-STROKE", "NIH Stroke Scale (NIHSS) - standard stroke assessment", "P1", "ninds",
     "https://www.ninds.nih.gov/health-information/public-education/know-stroke/health-professionals/nih-stroke-scale", "Free"),
    ("ESO-STROKE-2022", "ESO Guideline on IV Thrombolysis for Acute Ischemic Stroke 2022", "P1", "eso",
     "https://journals.sagepub.com/doi/full/10.1177/23969873221095817", "Free"),
    ("CN-NEUROSURGERY-2019", "Chinese Clinical Guidelines for Neurosurgery (中华神经外科指南)", "P0", "cns",
     "http://medjournals.cn/", "Chinese - journal access"),

    # --- Dermatology ---
    ("NRS-ROSACEA-2019", "National Rosacea Society Updated Classification 2019", "P0", "nrs",
     "https://www.rosacea.org/physicians/classification-of-rosacea", "Free"),
    ("AAD-ROSACEA-2024", "AAD Clinical Guideline on Rosacea Management", "P1", "aad",
     "https://www.aad.org/member/clinical-quality/guidelines/rosacea", "Free"),
    ("AAD-NPF-PSORIASIS-2020", "AAD/NPF Joint Guideline for Psoriasis Management 2020", "P0", "aad",
     "https://www.aad.org/member/clinical-quality/guidelines/psoriasis", "Free"),
    ("AAD-ALOPECIA", "AAD Alopecia Areata Clinical Guideline", "P1", "aad",
     "https://www.aad.org/member/clinical-quality/guidelines/alopecia-areata", "Free"),
    ("SKINDEX-29", "Skindex-29 Dermatology Quality of Life Instrument", "P2", "derm-qol",
     "https://pubmed.ncbi.nlm.nih.gov/9041721/", "Free validation reference"),
    ("CN-ROSACEA-2021", "Chinese Rosacea Diagnosis and Treatment Guideline 2021 (中国玫瑰痤疮指南)", "P0", "cmda",
     "http://medjournals.cn/", "Chinese - journal access"),

    # --- Ophthalmology ---
    ("AAO-GLAUCOMA-PPP", "AAO Preferred Practice Pattern - Primary Open-Angle Glaucoma", "P0", "aao",
     "https://www.aao.org/education/preferred-practice-pattern/primary-open-angle-glaucoma-ppp", "Free"),
    ("EGS-GLAUCOMA-2023", "European Glaucoma Society Guidelines 5th Ed 2023", "P1", "egs",
     "https://www.eugs.org/eng/guidelines.asp", "Free"),
    ("WGC-GLAUCOMA", "World Glaucoma Congress Consensus Statements", "P1", "wgc",
     "https://www.worldglaucoma.org/", "Free"),
    ("HODAPP-ANDERSON", "Hodapp-Parrish-Anderson Glaucoma Staging", "P2", "glaucoma",
     "https://pubmed.ncbi.nlm.nih.gov/8265702/", "Free - classic reference"),
    ("CN-GLAUCOMA-2025", "Chinese Glaucoma Guideline 2025 (中国青光眼指南)", "P0", "cjo",
     "http://medjournals.cn/", "Chinese - journal access"),

    # --- Dentistry / Stomatology ---
    ("FDI-NOTATION", "FDI World Dental Federation Two-Digit Notation", "P0", "fdi",
     "https://www.fdiworlddental.org/resources", "Free"),
    ("IAPD-GUIDELINES", "International Association of Paediatric Dentistry Guidelines", "P1", "iapd",
     "https://iapdworld.org/guidelines/", "Free"),
    ("ITI-CONSENSUS", "ITI International Team for Implantology Consensus", "P1", "iti",
     "https://www.iti.org/", "Free for members"),
    ("AO-ASIF-MAXILLOFACIAL", "AO/ASIF Classification of Maxillofacial Fractures", "P1", "aofoundation",
     "https://surgeryreference.aofoundation.org/cmf", "Free"),
    ("WS506-DENTAL-STERIL", "WS 506 Oral Medical Devices Sterilization Standard (口腔器械消毒灭菌规范)", "P0", "nhc-cn",
     "http://www.nhc.gov.cn/", "Free - Chinese national standard"),
    ("AAP-PERIO", "AAP Classification of Periodontal and Peri-Implant Diseases 2018", "P1", "aap",
     "https://www.perio.org/research-science/", "Free"),
    ("AAE-ENDO", "AAE Endodontic Clinical Treatment Guidelines", "P1", "aae",
     "https://www.aae.org/specialty/clinical-resources/guidelines-position-statements/", "Free"),
    ("CAO-ORTHO", "Chinese Association of Orthodontists Clinical Guidelines (中华口腔医学会正畸指南)", "P1", "csa",
     "http://www.cndent.com/", "Chinese - may require membership"),

    # --- Geriatrics ---
    ("AGS-BEERS-2023", "AGS Beers Criteria for Potentially Inappropriate Medication Use 2023", "P1", "ags",
     "https://agsjournals.onlinelibrary.wiley.com/doi/10.1111/jgs.18372", "Free"),
    ("STOPP-START-v3", "STOPP/START Criteria Version 3 for Prescribing Optimization", "P1", "eu-geri",
     "https://pubmed.ncbi.nlm.nih.gov/?term=STOPP+START+version+3", "Free"),
    ("FRIED-FRAILTY", "Fried Frailty Phenotype Criteria 2001", "P1", "jhu",
     "https://pubmed.ncbi.nlm.nih.gov/11253156/", "Free - landmark paper"),
    ("CGA-CONSENSUS-CN", "Chinese Expert Consensus on Comprehensive Geriatric Assessment (老年综合评估专家共识)", "P0", "cga",
     "http://medjournals.cn/", "Chinese - journal access"),
    ("ROCKWOOD-CFS", "Rockwood Clinical Frailty Scale", "P2", "dal",
     "https://www.dal.ca/sites/gmr/our-tools/clinical-frailty-scale.html", "Free"),
    ("BARTHEL-INDEX", "Barthel Index of Activities of Daily Living", "P2", "barthel",
     "https://pubmed.ncbi.nlm.nih.gov/?term=Barthel+index+reliability", "Free"),
    ("CN-ELDERLY-DM-2024", "Chinese Elderly Diabetes Guideline 2024 (中国老年糖尿病指南)", "P0", "cmda",
     "http://medjournals.cn/", "Chinese - journal access"),

    # --- Emergency Medicine ---
    ("ESI-TRIAGE-v4", "Emergency Severity Index (ESI) Version 4 Triage Algorithm", "P0", "ahrq",
     "https://www.ahrq.gov/patient-safety/settings/emergency-dept/esi.html", "Free"),
    ("MEWS-NEWS", "National Early Warning Score (NEWS2) 2017", "P1", "rcp",
     "https://www.rcplondon.ac.uk/projects/outputs/national-early-warning-score-news-2", "Free"),
    ("ACEP-POLICY", "ACEP Clinical Policies (Emergency Department)", "P2", "acep",
     "https://www.acep.org/patient-care/clinical-policies/", "Free"),
    ("CN-CHEST-PAIN-2022", "Chinese Acute Coronary Syndrome Emergency Guideline (急性冠脉综合征急诊指南)", "P0", "cec",
     "http://medjournals.cn/", "Chinese - journal access"),
    ("CN-STROKE-EMERGENCY", "Chinese Acute Ischemic Stroke Emergency Consensus (急性脑卒中急诊共识)", "P0", "cec",
     "http://medjournals.cn/", "Chinese - journal access"),
    ("CN-TRAUMA-SHOCK", "Chinese Trauma Hemorrhagic Shock Emergency Consensus (创伤失血性休克急诊共识)", "P1", "cec",
     "http://medjournals.cn/", "Chinese - journal access"),

    # --- Nursing ---
    ("BRADEN-SCALE", "Braden Scale for Predicting Pressure Sore Risk", "P1", "braden",
     "https://bradenscale.com/", "Free"),
    ("MORSE-FALL", "Morse Fall Scale - Hospital Fall Risk Assessment", "P1", "mfa",
     "https://pubmed.ncbi.nlm.nih.gov/?term=Morse+fall+scale+validation", "Free"),
    ("INS-INFUSION-2024", "INS Infusion Therapy Standards of Practice 2024", "P0", "ins",
     "https://www.ins1.org/publications/ins-standards-of-practice/", "Copyright - purchase"),
    ("JBI-EBN", "JBI Evidence-Based Nursing Manual", "P1", "jbi",
     "https://jbi.global/", "Free with institutional access"),
    ("ANA-STANDARDS", "ANA Nursing: Scope and Standards of Practice 4th Ed", "P2", "ana",
     "https://www.nursingworld.org/", "Copyright - purchase"),
    ("CN-NURSING-CAREER-PLAN", "China National Nursing Career Development Plan 2021-2025 (全国护理事业发展规划)", "P0", "nhc-cn",
     "http://www.nhc.gov.cn/", "Free - government document"),
    ("CN-NURSING-QUALITY", "China Nursing Sensitive Quality Indicators (护理敏感质量指标13项)", "P1", "nhc-cn",
     "http://www.nhc.gov.cn/", "Free - national monitoring standard"),

    # --- ENT / Otolaryngology ---
    ("AAO-HNS-VOICE", "AAO-HNS Clinical Practice Guideline: Hoarseness (Dysphonia)", "P0", "aao-hns",
     "https://www.entnet.org/quality-products/clinical-practice-guidelines/", "Free"),
    ("ELS-VOICE-SURGERY", "European Laryngological Society Phonosurgery Guidelines", "P1", "els",
     "https://www.elsoc.org/", "Free"),
    ("CAPE-V", "Consensus Auditory-Perceptual Evaluation of Voice (CAPE-V)", "P1", "asha",
     "https://www.asha.org/Form/CAPE-V/", "Free"),
    ("ASHA-VOICE-EVAL", "ASHA Voice Evaluation Protocol - American Speech-Language-Hearing Association", "P1", "asha",
     "https://www.asha.org/practice-portal/clinical-topics/voice-disorders/", "Free"),
    ("SVHI-10", "Singing Voice Handicap Index (SVHI-10)", "P2", "voice-institute",
     "https://pubmed.ncbi.nlm.nih.gov/?term=SVHI-10+singing+voice+handicap", "Free"),

    # --- Anesthesiology (missing department in xHAIP) ---
    ("ASA-PHYSICAL-STATUS", "ASA Physical Status Classification System 2020", "P0", "asa",
     "https://www.asahq.org/standards-and-practice-parameters/statement-on-asa-physical-status-classification-system", "Free"),
    ("ASA-FASTING-2023", "ASA Practice Guidelines for Preoperative Fasting 2023", "P0", "asa",
     "https://www.asahq.org/standards-and-practice-parameters", "Free"),
    ("ASA-DIFFICULT-AIRWAY-2022", "ASA Practice Guidelines for Management of the Difficult Airway 2022", "P1", "asa",
     "https://pubs.asahq.org/anesthesiology/article/doi/10.1097/ALN.0000000000004002", "Free"),
    ("MALLAMPATI", "Mallampati Classification of Upper Airway", "P1", "anesthesia",
     "https://pubmed.ncbi.nlm.nih.gov/4022173/", "Free - classic reference"),
    ("NAP5", "NAP5 UK National Audit of Airway Management Standards", "P2", "rcoa",
     "https://www.nationalauditprojects.org.uk/NAP5_home", "Free"),
    ("CN-SEDATION-ENDOSCOPY-2019", "Chinese Consensus on Sedation for GI Endoscopy (消化内镜镇静专家共识)", "P0", "cmda",
     "http://medjournals.cn/", "Chinese - journal access"),

    # --- Scoring & Assessment Tools (cross-disciplinary) ---
    ("CHA2DS2-VASC", "CHA2DS2-VASc Score - Stroke Risk in Atrial Fibrillation", "P0", "esc",
     "https://pubmed.ncbi.nlm.nih.gov/28886624/", "Free - ESC guideline standard"),
    ("HAS-BLED", "HAS-BLED Score - Bleeding Risk in Anticoagulated Patients", "P0", "esc",
     "https://pubmed.ncbi.nlm.nih.gov/21036840/", "Free - ESC guideline standard"),
    ("MEHRAN-RISK", "Mehran Risk Score for Contrast-Induced Nephropathy", "P0", "acc",
     "https://pubmed.ncbi.nlm.nih.gov/15216342/", "Free - landmark paper"),
    ("WELLS-DVT", "Wells Score for DVT Clinical Prediction", "P1", "wells",
     "https://pubmed.ncbi.nlm.nih.gov/12900679/", "Free"),
    ("WELLS-PE", "Wells Criteria for Pulmonary Embolism", "P1", "wells",
     "https://pubmed.ncbi.nlm.nih.gov/10744147/", "Free"),
    ("CAPRA-S", "CAPRA-S Score - Prostate Cancer Post-Surgical Risk", "P1", "urology",
     "https://pubmed.ncbi.nlm.nih.gov/21098445/", "Free"),
    ("CHARLSON-CCI", "Charlson Comorbidity Index (CCI) - original and updated", "P1", "comorbidity",
     "https://pubmed.ncbi.nlm.nih.gov/3558716/", "Free - landmark paper"),
    ("NUTRIC-SCORE", "NUTRIC Score for ICU Nutrition Risk", "P1", "icu",
     "https://pubmed.ncbi.nlm.nih.gov/21927559/", "Free"),
    ("PLASMIC-SCORE", "PLASMIC Score for TTP vs aHUS Discrimination", "P1", "ashe",
     "https://pubmed.ncbi.nlm.nih.gov/28514823/", "Free"),
    ("MASCC-RISK", "MASCC Risk Index for Febrile Neutropenia", "P1", "mascc",
     "https://pubmed.ncbi.nlm.nih.gov/10944139/", "Free"),
    ("KPS-ECOG", "Karnofsky (KPS) and ECOG Performance Status Scales", "P1", "ecog",
     "https://ecog-acrin.org/resources/ecog-performance-status/", "Free"),
    ("CLAVIEN-DINDO", "Clavien-Dindo Classification of Surgical Complications 2004/2009", "P1", "surgery",
     "https://pubmed.ncbi.nlm.nih.gov/15273542/", "Free"),
    ("APACHE-II", "APACHE II - Acute Physiology and Chronic Health Evaluation", "P2", "icu",
     "https://pubmed.ncbi.nlm.nih.gov/3928249/", "Free"),
    ("SOFA-SCORE", "SOFA - Sequential Organ Failure Assessment", "P1", "esicm",
     "https://pubmed.ncbi.nlm.nih.gov/8844239/", "Free"),

    # --- Chinese AI/Medical Device Regulations ---
    ("CN-MED-DEVICE-REG-2021", "Medical Device Supervision and Administration Regulations 2021 (医疗器械监督管理条例)", "P0", "sc-cn",
     "https://www.gov.cn/zhengce/content/2021-03/18/content_5593739.htm", "Free - government regulation"),
    ("CN-HUMAN-GENETIC-2019", "Regulations on Human Genetic Resources Management (人类遗传资源管理条例)", "P0", "sc-cn",
     "https://www.gov.cn/zhengce/content/2019-06/10/content_5398829.htm", "Free - government regulation"),
    ("CN-HEALTH-DATA-2018", "National Health and Medical Big Data Standards, Security and Service Measures (健康医疗大数据标准安全管理办法)", "P0", "nhc-cn",
     "http://www.nhc.gov.cn/", "Free - government regulation"),
    ("CN-INTERNET-MEDICAL", "Internet Diagnosis and Treatment Management Measures (互联网诊疗管理办法)", "P1", "nhc-cn",
     "http://www.nhc.gov.cn/", "Free - government regulation"),
    ("YYT-1833-2022", "YY/T 1833-2022 General Requirements for AI Medical Device Datasets (人工智能医疗器械数据集通用要求)", "P1", "nmpa",
     "https://www.nmpa.gov.cn/", "Industry standard - may require purchase"),
    ("YYT-1843-2022", "YY/T 1843-2022 Quality Requirements and Evaluation of AI Medical Devices (人工智能医疗器械质量要求与评价)", "P1", "nmpa",
     "https://www.nmpa.gov.cn/", "Industry standard - may require purchase"),

    # --- P2: Best Practices & Advanced Standards ---
    ("MODEL-CARD", "Model Cards for Model Reporting (Google 2019 standard)", "P2", "google",
     "https://arxiv.org/abs/1810.03993", "Free - AI transparency standard"),
    ("PRO-CTCAE", "PRO-CTCAE - Patient-Reported Outcomes version of CTCAE", "P2", "nci",
     "https://healthcaredelivery.cancer.gov/pro-ctcae/", "Free"),
    ("ICHOM-STANDARDS", "ICHOM Standard Sets for Patient-Centered Outcomes Measurement", "P2", "ichom",
     "https://www.ichom.org/standard-sets/", "Free"),
    ("CHEERS-2022", "CHEERS 2022 Consolidated Health Economic Evaluation Reporting Standards", "P2", "ispor",
     "https://www.ispor.org/heor-resources/good-practices/article/consolidated-health-economic-evaluation-reporting-standards-cheers-2022", "Free"),
    ("ISO-13606", "ISO 13606 Electronic Health Record Communication", "P2", "iso",
     "https://www.iso.org/standard/40784.html", "Copyright - purchase"),
    ("FHIR-GENOMICS", "HL7 FHIR Genomics Implementation Guide", "P2", "hl7",
     "https://hl7.org/fhir/uv/genomics-reporting/", "Free"),
    ("ICH-E6-R3", "ICH E6(R3) Guideline for Good Clinical Practice", "P1", "ich",
     "https://database.ich.org/sites/default/files/ICH_E6_R3_Step4_DraftGuideline_2023_0504.pdf", "Free PDF"),
    ("ICH-E2B-R3", "ICH E2B(R3) Electronic Transmission of Individual Case Safety Reports", "P2", "ich",
     "https://www.ich.org/page/e2br3-individual-case-safety-report-icsr-specification-and-related-files", "Free"),

    # --- Urology ---
    ("EAU-BLADDER-2026", "EAU Muscle-invasive Bladder Cancer 2026", "P0", "eau",
     "https://uroweb.org/guidelines/muscle-invasive-and-metastatic-bladder-cancer", "Free"),
    ("EAU-PROSTATE-2026", "EAU Prostate Cancer 2026", "P0", "eau",
     "https://uroweb.org/guidelines/prostate-cancer", "Free"),
    ("AUA-NLUTD-2021", "AUA/SUFU Adult Neurogenic LUTD 2021", "P1", "aua",
     "https://www.auanet.org/guidelines/neurogenic-lower-urinary-tract-dysfunction-guideline", "Free"),

    # --- Gastroenterology ---
    ("EASL-HCC-2018", "EASL Hepatocellular Carcinoma guideline", "P0", "easl",
     "https://www.journal-of-hepatology.eu/article/S0168-8278(18)32150-0/fulltext", "Free"),
    ("AASLD-HCC-2023", "AASLD HCC Practice Guidance 2023", "P0", "aasld",
     "https://journals.lww.com/hep/Fulltext/2023/12000", "Free"),
    ("ACG-FMT-2023", "ACG Clinical Guideline: Fecal Microbiota Transplantation", "P0", "acg",
     "https://journals.lww.com/ajg/Fulltext/2023/09000", "Free"),

    # --- Radiology ---
    ("BI-RADS", "ACR BI-RADS Atlas", "P0", "acr",
     "https://www.acr.org/Clinical-Resources/Reporting-and-Data-Systems/Bi-Rads", "Free"),
    ("LI-RADS", "ACR LI-RADS v2018", "P0", "acr",
     "https://www.acr.org/Clinical-Resources/Reporting-and-Data-Systems/LI-RADS", "Free"),
    ("Lung-RADS", "ACR Lung-RADS v2022", "P0", "acr",
     "https://www.acr.org/Clinical-Resources/Reporting-and-Data-Systems/Lung-Rads", "Free"),
    ("PI-RADS", "ACR PI-RADS v2.1", "P1", "acr",
     "https://www.acr.org/Clinical-Resources/Reporting-and-Data-Systems/PI-RADS", "Free"),
    ("TI-RADS", "ACR TI-RADS", "P1", "acr",
     "https://www.acr.org/Clinical-Resources/Reporting-and-Data-Systems/TI-RADS", "Free"),
    ("VI-RADS", "VI-RADS Bladder Imaging", "P0", "rsna",
     "https://pubs.rsna.org/doi/10.1148/radiol.2021210668", "Free"),
    ("ESUR-V10", "ESUR Contrast Agent Guidelines v10", "P0", "esur",
     "https://www.esur.org/esur-guidelines-on-contrast-agents/", "Free PDF"),

    # --- Pathology ---
    ("CAP-PROTOCOLS", "CAP Cancer Protocols (all systems)", "P0", "cap",
     "https://www.cap.org/protocols-and-guidelines/cancer-reporting-tools/cancer-protocols", "Free"),
    ("ICCR-DATASETS", "ICCR Cancer Reporting Datasets", "P0", "iccr",
     "https://www.iccr-cancer.org/datasets", "Free"),
    ("ASCO-CAP-HER2-2023", "ASCO/CAP HER2 Testing update 2023", "P1", "asco",
     "https://ascopubs.org/doi/10.1200/JCO.22.02864", "Free"),
    ("WHO-TUMOUR-V5", "WHO Classification of Tumours 5th Ed", "P0", "who",
     "https://publications.iarc.fr/", "Copyright - purchase required"),

    # --- Ob/Gyn ---
    ("FIGO-ENDOMETRIAL-2023", "FIGO Endometrial Cancer Staging 2023", "P0", "figo",
     "https://obgyn.onlinelibrary.wiley.com/doi/10.1002/ijgo.14930", "Free"),
    ("ESGO-ENDOMETRIAL-2021", "ESGO/ESTRO/ESP Endometrial Cancer guideline", "P0", "esgo",
     "https://ijgc.bmj.com/content/31/1/12", "Free"),
    ("NCCN-UTERINE-2025", "NCCN Uterine Neoplasms v1.2025", "P0", "nccn",
     "https://www.nccn.org/guidelines/guidelines-detail?category=1&id=1473", "Free registration"),

    # --- Pediatrics ---
    ("WHO-ENCC", "WHO Essential Newborn Care Course", "P0", "who",
     "https://www.who.int/publications/i/item/9789241507884", "Free PDF"),
    ("ELSO-GUIDELINES", "ELSO Guidelines for ECMO Centers", "P0", "elso",
     "https://www.elso.org/resources/guidelines.aspx", "Free"),
    ("AAP-HYPERBIL", "AAP Hyperbilirubinemia in Newborn guideline", "P1", "aap",
     "https://publications.aap.org/pediatrics/article/150/3/e2022058859/189666", "Free"),

    # --- Vascular ---
    ("ESVS-AAA-2024", "ESVS AAA Clinical Practice Guidelines 2024", "P0", "esvs",
     "https://www.ejves.com/article/S1078-5884(24)00593-1/fulltext", "Free"),
    ("SVS-AAA-2018", "SVS AAA Practice Guidelines 2018", "P1", "svs",
     "https://www.jvascsurg.org/article/S0741-5214(17)32304-5/fulltext", "Free"),
    ("ASH-VTE-2020", "ASH 2020 VTE Management Guidelines", "P1", "ash",
     "https://ashpublications.org/bloodadvances/article/4/19/4693/463998", "Free"),

    # --- Nutrition ---
    ("ESPEN-GUIDELINES", "ESPEN Clinical Nutrition Guidelines", "P0", "espen",
     "https://www.espen.org/guidelines-home/espen-guidelines", "Free PDF"),
    ("ASPEN-GUIDELINES", "ASPEN Clinical Guidelines", "P1", "aspen",
     "https://www.nutritioncare.org/Guidelines_and_Clinical_Resources/", "Free"),
    ("GLIM-2019", "GLIM Criteria for Malnutrition Diagnosis", "P1", "glim",
     "https://pubmed.ncbi.nlm.nih.gov/30175482/", "Free"),

    # --- ID/AMS ---
    ("IDSA-ASP-2016", "IDSA/SHEA Antibiotic Stewardship guideline", "P1", "idsa",
     "https://academic.oup.com/cid/article/62/10/e51/2462882", "Free"),
    ("CDC-AMS-2019", "CDC Core Elements of Hospital Antibiotic Stewardship", "P1", "cdc",
     "https://www.cdc.gov/antibiotic-use/core-elements/hospital.html", "Free"),
    ("CLSI-M100", "CLSI M100 AST Performance Standards", "P0", "clsi",
     "https://clsi.org/standards/products/microbiology/documents/m100/", "Copyright - purchase"),
    ("EUCAST-V14", "EUCAST Clinical Breakpoints v14", "P1", "eucast",
     "https://www.eucast.org/clinical_breakpoints", "Free"),

    # --- Pharmacy ---
    ("ASHP-STANDARDS", "ASHP Pharmacy Practice Guidelines", "P1", "ashp",
     "https://www.ashp.org/pharmacy-practice/policy-positions-and-guidelines", "Free"),
    ("CPIC-GUIDELINES", "CPIC Pharmacogenomics Guidelines", "P0", "cpic",
     "https://cpicpgx.org/guidelines/", "Free"),
    ("WFH-HEMOPHILIA", "WFH Hemophilia Management Guidelines 3rd Ed", "P0", "wfh",
     "https://www.wfh.org/en/resources/wfh-treatment-guidelines", "Free PDF"),
    ("ISMP-HIGH-ALERT", "ISMP High-Alert Medications List", "P0", "ismp",
     "https://www.ismp.org/recommendations/high-alert-medications-acute-list", "Free"),

    # --- Management ---
    ("ISO-15189-2022", "ISO 15189:2022 Medical laboratories", "P0", "iso",
     "https://www.iso.org/standard/76677.html", "Copyright - purchase"),
    ("WHO-PATIENT-SAFETY", "WHO Global Patient Safety Action Plan", "P1", "who",
     "https://www.who.int/publications/i/item/9789240032705", "Free PDF"),
    ("SQUIRE-2.0", "SQUIRE 2.0 Quality Improvement Reporting", "P1", "squire",
     "https://www.squire-statement.org/", "Free"),
    ("JCI-7TH", "JCI Accreditation Standards 7th Ed", "P1", "jci",
     "https://www.jointcommissioninternational.org/", "Copyright - purchase"),
]

# --- Write all reference entries ---
count = 0
for sid, title, priority, source, url, note in ALL_STANDARDS:
    entry = {
        "id": sid,
        "title": title,
        "priority": priority,
        "source": source,
        "url": url,
        "note": note,
        "downloaded": False,
        "generated": datetime.now().isoformat(),
    }
    fpath = OUTPUT / f"{sid}-ref.json"
    fpath.write_text(json.dumps(entry, indent=2, ensure_ascii=False), encoding="utf-8")
    count += 1

print(f"Generated {count} reference entries in {OUTPUT}")
print(f"Total files in output: {len(list(OUTPUT.glob('*')))}")
